apiVersion: v1
kind: ConfigMap
metadata:
  name: whiteboard-config
data:
  db-host: "postgres-service"
  db-port: "5432"
  db-name: "whiteboard_db"
  spring-profiles-active: "production"
  redis-host: "redis-service"
  redis-port: "6379"
