apiVersion: v1
kind: Secret
metadata:
  name: whiteboard-secrets
type: Opaque
data:
  db-username: <base64-encoded-username>
  db-password: <base64-encoded-password>
  redis-password: <base64-encoded-redis-password>
