apiVersion: v1
kind: Service
metadata:
  name: whiteboard-nodeport
  labels:
    app: whiteboard-backend
spec:
  type: NodePort
  selector:
    app: whiteboard-backend
  ports:
  - name: http
    port: 80
    targetPort: 8080
    nodePort: 30080
    protocol: TCP
  - name: websocket
    port: 8081
    targetPort: 8080
    nodePort: 30081
    protocol: TCP
